### PR TITLE
fix #294 per ion savitzky golay for msd data

### LINKED ISSUE #294: Savitzky-Golay on ion signals
Implement a Savitzky-Golay filter for mass spectrometry chromatograms that operates on individual ion channels.

### PR DESCRIPTION
**Pull request by lorenzgerber**
Signed-off-by: Lorenz Gerber <lorenz.gerber@lablicate.com>

### CODE REVIEW

**Review by laeubi — APPROVED** [review]

**Comment by eselmeister** [comment]
One error shows up in my workspace:
Description	Resource	Location	Path	Type
The method setPerIonCalculation(boolean) is undefined for the type MassSpectrumFilterSettings	PreferenceSupplier.java	line 100	/org.eclipse.chemclipse.chromatogram.xxd.filter.supplier.savitzkygolay/src/org/eclipse/chemclipse/chromatogram/xxd/filter/supplier/savitzkygolay/preferences	Java Problem

I will fix it now.

**Comment by eselmeister** [comment]
The "setPerIonCalculation" flag is set for the MassSpectrumFilterSettings instead of the ChromatogramFilterSettings.

`	public static ChromatogramFilterSettings getFilterSettings() {

		IEclipsePreferences preferences = INSTANCE().getPreferences();
		ChromatogramFilterSettings filterSettings = new ChromatogramFilterSettings();
		filterSettings.setOrder(preferences.getInt(P_ORDER, DEF_ORDER));
		filterSettings.setWidth(preferences.getInt(P_WIDTH, DEF_WIDTH));
		return filterSettings;
	}

	public static MassSpectrumFilterSettings getMassSpectrumFilterSettings() {

		MassSpectrumFilterSettings settings = new MassSpectrumFilterSettings();
		settings.setOrder(getOrder());
		settings.setWidth(getWidth());
		settings.setPerIonCalculation(getPerIonCalculation());
		return settings;
	}`

Was that intentionally?

**Comment by eselmeister** [comment]
@lorenzgerber When working on the code, please update the copyright header correctly:

2015, 2018, 2020 Lablicate GmbH <- wrong
2015, 2020 Lablicate GmbH <- correct

**Comment by laeubi** [comment]
@eselmeister Its a little bit strange to give review-comment **after** merging a pullrequest, the intent is to clarify and fix such issues (by the author) **before** merging into the main codebase.
If you like to review changes locally you can find information here how to checkout a Pull-Request into a local branch: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally

**Comment by eselmeister** [comment]
@laeubi Thanks for your wonderful tip. It's mysterious, why you have approved the changes 13 hours ago? Haven't you checked and tested the code?

**Comment by laeubi** [comment]
I'm glad I can help you. As you probably has noticed there was a previous PR that failed due to IP-problems what I reviewed, commented and was improved by @lorenzgerber and he then opened this one to clear the IP-problem. Seems something has changed in between while opening the new one, anyways, as many eyes see more than two, I have requested another review from you and @kerner1000 to make sure I have not overseen some points.

Beside that others people unawareness doesn't change the general way how code-reviews work, to the greatest mysterious from my point of view is why you always trying to find reasons for accusations if someone is giving you a hint, so I can only again ask to stay professional on technical topics.

**Comment by eselmeister** [comment]
Your "help" is appreciated, but I kindly ask you in return to stay professional. There is a difference between contributors, committers and project leads. You are a project lead. I mistakenly assumed that you already have reviewed the code correctly. It seems, that you only had a look at the diff instead of applying a patch in the current "develop" workspace, compile, test and run it against a real chromatogram to validate if there are any issues. So, this has nothing to do with accusations. It was my mistake, that I didn't double checked your approval, as I assumed that you have performed the following code-review steps:

A) Review the PR - are the checks green
B) Review the code - copyright headers correct? code formatted? obvious errors?
C) Merge the code locally in the "develop" workspace via "...chemclipse/pull/299.patch"
D) Run ChemClipse and test it with real world data

If everything is fine, then merge the code.

Thanks.

**Comment by laeubi** [comment]
Thats why I have not merged the code, so others can review, comment and probably suggest changes. So of course there is accusation, as you have merged without any checks (and making it further impossible to improve the PR) and afterwards complains that there is something missing because you have assumed everything is just fine.
As other place mentioned: your also project lead of eclipse as of now: So pressing the "merge" button is not what would be expected if someone adding you as a reviewer to the pull-request...

**Comment by eselmeister** [comment]
@laeubi Which of the mentioned steps A) - D) have you performed before you have approved this PR?

**Comment by laeubi** [comment]
For your reference see https://github.com/eclipse/chemclipse/pull/298 on original discussion about code and improvements discussed with @lorenzgerber as he has very good knowledge about the chemical and analytical background I have no reason to believe that the methodology per-se is wrong and the code looks right from a programmers perspective I approved it.
 To be sure, and get another opinion, I requested review from you @eselmeister as another expert for the chemical part and @kerner1000 for maybe other insights.
So my I then ask why do you accuse me for not following your rules if you haven't obviously either have passed below "checks are green" before pressing merge?

**Comment by eselmeister** [comment]
@laeubi That's not an answer to my question.

**Pull request merged**
