### PR TITLE
Cleaned up MassSpectrumIdentifier and SampleQuantProcessor

### PR DESCRIPTION
**Pull request by Mailaender**
This contains no real change.

### CODE REVIEW

**Comment by eselmeister** [comment]
Adding the "`return false`" statements in the class `MassSpectrumIdentifier` changes the process logic. If such a case would have been intended, it would have been easier to simply write:

```
return supplier.isImportable();
```

But this would also change the process logic. As soon as the first supplier doesn't support the import, the check of all others is skipped as false is immediately returned. That's why only "true" is returned if the current supplier support the import. In all other cases, test each supplier until at least one supplier is available to support the import. The method return "`false`" at its end if no previous action returned true.

**Comment by Mailaender** [comment]
Correct. Well spotted.

**Comment by eselmeister** [comment]
The problem remains. It's the logic of the return statement. It could be, that the supplier matches, but that it is not importable. In such a case, false would be returned and all other supplier checks will be skipped.

**Comment by Mailaender** [comment]
There is no logic change in there. See https://rules.sonarsource.com/java/RSPEC-1126 for the violation.

**Comment by eselmeister** [comment]
For the pure statement `return supplier.isImportable();` this is correct. But it's the for loop that matters here:

```
for(ISupplier supplier : suppliers) {
	directoryExtension = supplier.getDirectoryExtension().toUpperCase();
	if(!directoryExtension.isEmpty() && directory.endsWith(directoryExtension)) {
		return supplier.isImportable();
	}
}
```
Imagine the `directoryExtension` is not empty and all supplier match the `directoryExtension`. Additionally, imagine we have three suppliers, but the first supplier doesn't have import capabilities:

- Supplier A - Importable: false
- Supplier B - Importable: true
- Supplier C - Importable: true

Then B and C will never be checked, as `supplier.isImportable();` returns `false` for the Supplier A.

**Comment by Mailaender** [comment]
Updated.

**Comment by eselmeister** [comment]
You are right. The logic was already wrong in the basic version. It seems, that something is odd with this class. I'll take care of it.

**Pull request merged**
