### PR TITLE
Set required mzML defaultArrayLength

### PR DESCRIPTION
**Pull request by Mailaender**
This is a followup to https://github.com/eclipse/chemclipse/pull/852.

### CODE REVIEW

**Comment by bspratt** [comment]
Those changes look promising - can you re-run that conversion and send me a link to the result?

**Comment by Mailaender** [comment]
https://share.lablicate.com/index.php/s/3fNrdw3q95PiRnp

**Comment by bspratt** [comment]
Looks good - I can view it in SeeMS with my patch for tolerating zero length scans (that should show up in tomorrow's release at https://proteowizard.sourceforge.io/download.html). 

Ideally you would also populate each scan's base peak m/z, base peak intensity, and total ion current, e.g.

          <cvParam cvRef="MS" accession="MS:1000505" name="base peak intensity" value="1196.0" unitCvRef="MS" unitAccession="MS:1000131" unitName="number of detector counts"/>
          <cvParam cvRef="MS" accession="MS:1000504" name="base peak m/z" value="328.049513705619" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
          <cvParam cvRef="MS" accession="MS:1000285" name="total ion current" value="9941.0" unitCvRef="MS" unitAccession="MS:1000131" unitName="number of detector counts"/>


Also setting the spectrum type is good practice, e.g.

          <cvParam cvRef cvRef="MS" accession="MS:1000579" name="MS1 spectrum" value=""/>

or, where mslevel is greater than 1,

        <cvParam cvRef="MS" accession="MS:1000580" name="MSn spectrum" value=""/>

**Comment by Mailaender** [comment]
Updated.

**Comment by bspratt** [comment]
These changes look good. Can you post another converter output file?

**Comment by Mailaender** [comment]
https://share.lablicate.com/index.php/s/Q5TNSRDQfMm4Ffc 

Note that this increases file size by ~ 40 %.

**Comment by bspratt** [comment]
Looks great!

> Note that this increases file size by ~ 40 %.

Yes, mzML is terribly verbose.

**Comment by Mailaender** [comment]
https://github.com/OpenChrom/openchrom/wiki/Changelog#202112230244 a new version containing this fix has been released. Happy holidays. :christmas_tree:

**Comment by bspratt** [comment]
Echt gut. Fröhliche Weihnachtszeit!

**Pull request merged**
