### PR TITLE
Changed the default colors of the welcome screen

### LINKED ISSUE #725: Default colors of the welcome screen are unpleasant
Green

This weird Windows 98 desktop background green is seen nowhere else in the platform. It is an extremely irritating first impression.

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/eclipse/chemclipse/issues/725.

### CODE REVIEW

**Comment by eselmeister** [comment]
Principally, I agree that the contrast in the welcome screen could be improved. The gray version looks IMHO cold and inactive. Let's play with some color schemes and activate the new welcome color along with the Java 11 / Eclipse Latest release. It's then reasonable, that something has been changed/improved.

**Comment by eselmeister** [comment]
Bildschirmfoto von 2021-09-07 09-07-06

IMHO, it has a cementary look & feel.

**Comment by Mailaender** [comment]
I tried to be visually consistent with the overall white/gray look of ChemClipse

Screenshot_20210909_142236

but indeed I am not a designer.

**Comment by Mailaender** [comment]
Updated the colors slightly.

**Comment by Mailaender** [comment]
I agree, the gray is boring. Updated the color scheme to match the :red_square: logo/icon

image

Also, the description text is now themed. It was hard to read.

**Pull request merged**
