### PR TITLE
Fixed the .ocb detector iterating over each file 3x regardless of file extension

### PR DESCRIPTION
**Pull request by Mailaender**
This is a long shot on https://github.com/OpenChrom/openchrom/issues/101. I haven't profiled this.

### CODE REVIEW

**Comment by eselmeister** [comment]
@Mailaender You could also use the method:

`checkFileExtension(file, ".ocb");`

We might also remove the option "isForceLoadAlternateDetector()". GC-FID is fully supported meanwhile.

**Comment by Mailaender** [comment]
Updated.

**Comment by eselmeister** [comment]
@Mailaender Please update the year in the copyright header. Additionally, the flag "P_FORCE_LOAD_ALTERNATE_DETECTOR" is marked to be removed. Hence, have a look at the CSD, MSD and WSD magic code matcher to remove the alternate functionality consistently.

**Comment by Mailaender** [comment]
Updated.

**Comment by eselmeister** [comment]
@Mailaender Looks good. Just another small change request. To understand the code, I would recommend to keep the comment:

```
/*
 * Legacy:
 * DIR_CHROMATOGRAM
 * Versions <= 0.9.0.3
 */
```

Otherwise, it's hard to understand why a folder DIR_CHROMATOGRAM shall be supported.

**Comment by Mailaender** [comment]
Kept the comment.

**Pull request merged**
