### PR TITLE
Fixed a regression in column type labeling

### LINKED ISSUE #803: Unhandled event loop exception in Retention Index Calculator
> ERROR	Retention Index Calculator	The retention index map could not be found. Is a calibration (*.cal) file or chromatogram RI map available?

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/eclipse/chemclipse/issues/803

### CODE REVIEW

**Comment by eselmeister** [comment]
I was not able to reproduce the error so far. The error message is thrown in the `calculateIndices(...)` method of the class:
`org.eclipse.chemclipse.chromatogram.xxd.calculator.supplier.amdiscalri.impl.RetentionIndexCalculator`

IMHO, I doubt that the runnable is involved here. It seems to be, that the RI entries can't be fetched:

```
ISeparationColumnIndices separationColumnIndices = getSeparationColumnIndices(chromatogramSelection, calculatorSettings);
if(separationColumnIndices != null) {
	...
} else {
	processingInfo.addErrorMessage(DESCRIPTION, "The retention index map could not be found. Is a calibration (*.cal) file or chromatogram RI map available?");
}
```

We could try to delete the user preference and start the process again.

**Comment by Mailaender** [comment]
Hmm, yes this only seems to swallow the exception, no RIs are calculated and it still shows errors. See https://github.com/eclipse/chemclipse/issues/803#issuecomment-957479286

**Comment by Mailaender** [comment]
Okay, I can now confirm that this calculates retention indices again.

**Comment by eselmeister** [comment]
Is it on purpose that `SEMI-POLAR` is flipped in `SeparationColumnType`?

```
DEFAULT("Default", "DEFAULT"), //
POLAR("Polar", "POLAR"), //
APOLAR("Nonpolar", "APOLAR"), //
SEMI_POLAR("SEMI-POLAR", "Semipolar"),
```

**Comment by Mailaender** [comment]
No, I was hasty there. Fixed.

**Pull request merged**
