### PR TITLE
Remove OpenChrom trademark

### PR DESCRIPTION
**Pull request by Mailaender**
like https://github.com/eclipse/chemclipse/pull/860 did.

### CODE REVIEW

**Comment by eselmeister** [comment]
Isn't a correct automatic module name required?
```
org.eclipse.chemclipse.xxd.identifier.supplier.wikidata.ui
...
```

**Comment by Mailaender** [comment]
Apparently not when it was the wrong one all the time.

**Comment by eselmeister** [comment]
Probably, it's better to set the correct one instead of none to be consistent with all other bundles.

**Comment by Mailaender** [comment]
Fixed it in a few other occasions.

**Pull request merged**
