### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by operagxoksana**
Update README

### CODE REVIEW

**Comment by eselmeister** [comment]
@operagxoksana Thanks for your commit. You need to login at Eclipse and sign the ECA, see above details.

**Comment by operagxoksana** [comment]
Zavdzhi is glad to catch up.
Already signed

**Comment by eselmeister** [comment]
@operagxoksana The ECA check still fails. The author/committer email must be matched. You might need to link your GitHub account in Eclipse.

**Comment by operagxoksana** [comment]
I don't understand the reason, the e-mail address matches!

**Pull request closed without merging**
