### PR TITLE
Fixed toolbars icons being duplicated

### PR DESCRIPTION
**Pull request by Mailaender**
making them hard to differentiate.

### CODE REVIEW

**Comment by eselmeister** [comment]
The proposed changes look good. But the integration icon is needed:
`String IMAGE_INTEGRATION_RESULTS = PATH_PREFIX + "integrationResults.gif";`

Even if integration and quantitation have the same icons at the moment, both are different process steps.

**Comment by Mailaender** [comment]
I reused `IMAGE_CHROMATOGRAM_INTEGRATOR` instead.

**Comment by eselmeister** [comment]
The `IMAGE_CHROMATOGRAM_INTEGRATOR` shall indicate, which kind of integrator is used.
chromatogramIntegrator

The `IMAGE_INTEGRATION_RESULTS` image is used to display that a certain result is available:
integrationResults

It would be great if we could keep the integration results image.

**Comment by Mailaender** [comment]
Removed the change.

**Pull request merged**
