### PR TITLE
Added basic support for PCA with MALDI-TOF spectra

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/OpenChrom/OpenTyper/issues/12.

### CODE REVIEW

**Comment by eselmeister** [comment]
@Mailaender Please adjust the copyright header. Instead of listing all years "2017, 2020, 2021 Lablicate GmbH." just use start year, stop year -> "2017, 2021 Lablicate GmbH."

**Comment by Mailaender** [comment]
Rebased, signed the commits, updated the copyright header range and fixed the variable name in the Feature Table.

**Comment by eselmeister** [comment]
@Mailaender Please update the copyright header to 2021 in the following classes:

- QuickStartPart
- DataType
- DataCategory
- DataCategoryGroup
- IChemClipseEvents
- OverviewSupport
- SupplierEditorSupport

**Comment by Mailaender** [comment]
Updated the copyright headers.

**Pull request merged**
