### PR TITLE
Added native toggle buttons

### PR DESCRIPTION
**Pull request by Mailaender**
https://github.com/eclipse/chemclipse/issues/1447 inspired me to rework the icons. Instead of overlaying a :red_circle: I simply used [SWT toggle buttons](https://www.eclipse.org/swt/widgets/). This also allows tracking the state on the button and feels less alien to the user. The `MDirectToolItem` will ignore the check state when it also gets a menu, so I repainted the icons with a dark inactive state. Not having 25% of them covered with a red dot on a red icon makes them a bit easier to distinguish.

### CODE REVIEW

**Comment by eselmeister** [comment]
That looks principally good. But the icons in the main toolbar are grey, so people might think they are disabled.

Screenshot from 2023-07-11 16-08-51

**Comment by Mailaender** [comment]
What do you suggest instead?

**Comment by eselmeister** [comment]
Is it possible to keep the color of the icon, so that it behaves like the breakpoint toggle in Eclipse?

Screenshot from 2023-07-11 22-02-31

Screenshot from 2023-07-11 22-02-36

When the category is active, the gray background shall be displayed.

**Comment by Mailaender** [comment]
> The `MDirectToolItem` will ignore the check state when it also gets a menu...

**Comment by Mailaender** [comment]
I tried hacking around this using a checked button and fake dropdown next to it in a tool control, which, however, required a lot of custom code and gave very flaky results. I now pasted the Eclipse pin needle into the icons, similar to the legacy ones.

**Comment by eselmeister** [comment]
The changes of this PR have been cherry-picked and pushed via:
https://github.com/eclipse/chemclipse/issues/1460

**Pull request closed without merging**
